//! Golden-vector tests pinning the `fedi-trust-score-v1.0` wire shape.
//!
//! The fixture is a fully signed artifact set with checked-in test keys.
//! Downstream repos verify the same fixture through their own stacks, so a
//! change that breaks it is a cross-repo wire break, not a refactor.
//!
//! Regenerate with:
//! `REGENERATE_GOLDEN=1 cargo test -p peerbadge-schemas --test golden`
//! then run the tests again without the variable: the validating tests compare
//! against the fixture embedded at compile time, so a regeneration run always
//! validates the previous fixture, not the one it just wrote.

use peerbadge_protocol::{
    HolderAuthorization, HolderAuthorizationRequest, HolderContext, IssuerAuthority,
    IssuerContext, IssuerSecretKeys, PendingIssuance, RevocationLocation, SignedCredential,
    SubjectPubkey, VerificationContext,
};
use peerbadge_schemas::{
    parse_trust_score_badge_v1, trust_score_blind_msg_v1, trust_score_info_v1,
};
use serde::{Deserialize, Serialize};

const FIXTURE: &str = include_str!("../fixtures/trust-score-v1.json");
const APP_ISSUED_FIXTURE: &str = include_str!("../fixtures/app-issued-vector.json");
const FIXTURE_TRUST_LEVEL: u64 = 9;
const FIXTURE_ISSUED_AT: u64 = 1_754_784_000; // 2025-08-10T00:00:00Z, fixed
const FIXTURE_SUBJECT_HEX: &str =
    "c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5";

/// Test-only key material and signed artifacts. Never reuse these keys.
#[derive(Serialize, Deserialize)]
struct GoldenVector {
    issuer_secret_keys: IssuerSecretKeys,
    holder_secret_key: String,
    issuer_authority: IssuerAuthority,
    signed_credential: SignedCredential,
    holder_authorization: HolderAuthorization,
}

fn load_vector() -> GoldenVector {
    serde_json::from_str(FIXTURE).expect("golden vector deserializes")
}

#[test]
fn golden_vector_verifies_and_parses() {
    let vector = load_vector();

    let mut context = VerificationContext::new();
    context
        .add_issuer_authority(&vector.issuer_authority)
        .expect("authority is accepted");
    context
        .verify_credential(&vector.signed_credential)
        .expect("credential verifies");
    context
        .verify_credential_authorization_at_time(
            &vector.signed_credential,
            &vector.holder_authorization,
            FIXTURE_ISSUED_AT,
        )
        .expect("holder authorization verifies");

    let badge = parse_trust_score_badge_v1(&vector.signed_credential.credential)
        .expect("badge parses under fedi-trust-score-v1.0");
    assert_eq!(badge.trust_level, FIXTURE_TRUST_LEVEL);

    let holder = HolderContext::import_secret_key(&vector.holder_secret_key)
        .expect("holder key imports");
    assert_eq!(badge.holder_pubkey, holder.public_key());
}

/// Badge captured from the credential-app's own issuance path (public
/// material only). Unlike [`GoldenVector`], this was NOT generated by this
/// crate, so it breaks the circularity of the SDK verifying its own output:
/// it is the shipped app's actual behavior, not this crate's transcription of
/// it. Captured once by `appIssuedBadge.browser.test.ts` in the credential-app
/// repo; deliberately never regenerated from here.
#[derive(Deserialize)]
struct AppIssuedVector {
    issuer_authority: IssuerAuthority,
    signed_credential: SignedCredential,
    holder_pubkey: String,
}

#[test]
fn app_issued_badge_verifies_and_parses() {
    let vector: AppIssuedVector =
        serde_json::from_str(APP_ISSUED_FIXTURE).expect("app-issued vector deserializes");

    let mut context = VerificationContext::new();
    context
        .add_issuer_authority(&vector.issuer_authority)
        .expect("authority is accepted");
    context
        .verify_credential(&vector.signed_credential)
        .expect("app-issued credential verifies");

    let badge = parse_trust_score_badge_v1(&vector.signed_credential.credential)
        .expect("app-issued badge parses under fedi-trust-score-v1.0");
    assert_eq!(badge.trust_level, 9);
    assert_eq!(badge.holder_pubkey.to_string(), vector.holder_pubkey);
}

#[test]
fn issuance_with_fixture_keys_reproduces_the_golden_payload() {
    let vector = load_vector();

    let issuer = IssuerContext::import_secret_key(&vector.issuer_secret_keys)
        .expect("issuer keys import");
    let holder = HolderContext::import_secret_key(&vector.holder_secret_key)
        .expect("holder key imports");

    let reproduced = issue(&issuer, &vector.issuer_authority, &holder);

    // PBRSA signatures are not deterministic across issuance runs, so compare
    // the signed payload and prove the fresh proof verifies instead.
    assert_eq!(
        reproduced.credential, vector.signed_credential.credential,
        "issuance with the fixture keys must reproduce the golden credential payload"
    );

    let mut context = VerificationContext::new();
    context
        .add_issuer_authority(&vector.issuer_authority)
        .expect("authority is accepted");
    context
        .verify_credential(&reproduced)
        .expect("reproduced credential verifies");
}

fn issue(
    issuer: &IssuerContext,
    authority: &IssuerAuthority,
    holder: &HolderContext,
) -> SignedCredential {
    let info = trust_score_info_v1(FIXTURE_TRUST_LEVEL).expect("legal level");
    let blind_msg = trust_score_blind_msg_v1(&holder.public_key());

    let (request, pending) = PendingIssuance::create_request(
        &authority.issuer.issuance_key,
        authority.issuer.issuer_id_pubkey.clone(),
        info.clone(),
        blind_msg,
    )
    .expect("request creation succeeds");
    let response = issuer
        .issue_credential(info, &request)
        .expect("issuance succeeds");
    pending
        .finalize(&authority.issuer.issuance_key, &response)
        .expect("finalize succeeds")
}

#[test]
fn regenerate_golden_vector() {
    if std::env::var_os("REGENERATE_GOLDEN").is_none() {
        return;
    }

    let issuer = IssuerContext::generate().expect("issuer generates");
    let holder = HolderContext::generate();
    // Same revocation-location set the shipped PeerBadge issuer pins, so the
    // vector's authority matches production-shaped authorities.
    let revocation = vec![
        RevocationLocation {
            protocol: "nostr".to_owned(),
            location: "wss://nostr-rs-relay.dev.fedibtc.com".to_owned(),
        },
        RevocationLocation {
            protocol: "nostr".to_owned(),
            location: "wss://relay.damus.io/".to_owned(),
        },
    ];
    let issuer_authority = issuer
        .issuer_authority(revocation)
        .expect("authority builds");
    let signed_credential = issue(&issuer, &issuer_authority, &holder);
    let holder_authorization = holder
        .authorize_credential_use_at_time(
            HolderAuthorizationRequest {
                subject_pubkey: SubjectPubkey(
                    nostr::PublicKey::parse(FIXTURE_SUBJECT_HEX).expect("valid subject key"),
                ),
            },
            &signed_credential,
            FIXTURE_ISSUED_AT,
        )
        .expect("authorization signs");

    let vector = GoldenVector {
        issuer_secret_keys: issuer.export_secret_key().expect("keys export"),
        holder_secret_key: holder.export_secret_key(),
        issuer_authority,
        signed_credential,
        holder_authorization,
    };

    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/trust-score-v1.json");
    let mut serialized = serde_json::to_string_pretty(&vector).expect("vector serializes");
    serialized.push('\n');
    std::fs::write(path, serialized).expect("fixture writes");
}
